language: python
python:
  - "3.5"

env:
    global:
        - SPARK_HOME=/tmp/spark-2.0.2-bin-hadoop2.7

# command to install dependencies
install:
  - ./install-spark.sh
  - "pip install -r requirements.txt"


# command to run tests
script:
  - export PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.10.3-src.zip:$PYTHONPATH
  - python -m unittest discover